import { PrismaClient, Store } from '@prisma/client';

interface BannerData {
  title: string;
  description?: string;
  imageUrl: string;
  imageUrlTablet?: string;
  imageUrlMobile?: string;
  ctaText?: string;
  ctaUrl?: string;
  ctaTarget?: '_self' | '_blank';
  placement: 'homepage_hero' | 'section_banner' | 'collection_banner' | 'announcement_bar';
  status: 'draft' | 'active' | 'scheduled' | 'inactive';
  startDate?: Date;
  endDate?: Date;
  priority: number;
  sortOrder: number;
  backgroundColor?: string;
  textColor?: string;
  overlayOpacity?: number;
  metadata?: Record<string, unknown>;
}

// Ramlit Limited - IT Services, AI, DevOps, Cloud Technology
const ramlitBanners: BannerData[] = [
  // Homepage Hero Banners
  {
    title: 'Transform Your Business with AI',
    description: 'Leverage cutting-edge artificial intelligence to automate processes, gain insights, and drive innovation across your organization.',
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1920&h=800&fit=crop',
    imageUrlTablet: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1024&h=600&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=640&h=800&fit=crop',
    ctaText: 'Explore AI Solutions',
    ctaUrl: '/products?category=ai-solutions',
    placement: 'homepage_hero',
    status: 'active',
    priority: 100,
    sortOrder: 0,
    backgroundColor: '#0a0a0a',
    textColor: '#ffffff',
    overlayOpacity: 40,
  },
  {
    title: 'Cloud Infrastructure at Scale',
    description: 'Deploy, manage, and optimize your cloud workloads with our enterprise-grade solutions for AWS, Azure, and Google Cloud.',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1920&h=800&fit=crop',
    imageUrlTablet: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1024&h=600&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=640&h=800&fit=crop',
    ctaText: 'View Cloud Services',
    ctaUrl: '/products?category=cloud-services',
    placement: 'homepage_hero',
    status: 'active',
    priority: 90,
    sortOrder: 1,
    backgroundColor: '#1a1a2e',
    textColor: '#ffffff',
    overlayOpacity: 35,
  },
  {
    title: 'DevOps Excellence',
    description: 'Streamline your development pipeline with CI/CD automation, Kubernetes orchestration, and infrastructure as code.',
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1920&h=800&fit=crop',
    imageUrlTablet: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1024&h=600&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=640&h=800&fit=crop',
    ctaText: 'Accelerate Delivery',
    ctaUrl: '/products?category=devops',
    placement: 'homepage_hero',
    status: 'active',
    priority: 80,
    sortOrder: 2,
    backgroundColor: '#16213e',
    textColor: '#ffffff',
    overlayOpacity: 45,
  },
  // Section Banners
  {
    title: 'Enterprise Security Solutions',
    description: 'Protect your digital assets with our comprehensive security services.',
    imageUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1200&h=400&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=640&h=400&fit=crop',
    ctaText: 'Learn More',
    ctaUrl: '/services',
    placement: 'section_banner',
    status: 'active',
    priority: 50,
    sortOrder: 0,
    backgroundColor: '#1e3a5f',
    textColor: '#ffffff',
    overlayOpacity: 30,
  },
  {
    title: 'Free Consultation for Startups',
    description: 'Get a complimentary 1-hour consultation on your technology strategy.',
    imageUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&h=400&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=640&h=400&fit=crop',
    ctaText: 'Book Now',
    ctaUrl: '/contact',
    placement: 'section_banner',
    status: 'active',
    priority: 45,
    sortOrder: 1,
    backgroundColor: '#2d3436',
    textColor: '#ffffff',
    overlayOpacity: 25,
  },
  // Collection Banners
  {
    title: 'AI & Machine Learning',
    description: 'Discover our complete suite of AI solutions',
    imageUrl: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&h=600&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=400&h=400&fit=crop',
    ctaText: 'Browse Collection',
    ctaUrl: '/products?category=ai-solutions',
    placement: 'collection_banner',
    status: 'active',
    priority: 40,
    sortOrder: 0,
    backgroundColor: '#0f0f23',
    textColor: '#ffffff',
    overlayOpacity: 35,
  },
  {
    title: 'Cloud & Infrastructure',
    description: 'Scalable solutions for modern enterprises',
    imageUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&h=600&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=400&h=400&fit=crop',
    ctaText: 'Explore Services',
    ctaUrl: '/products?category=cloud-services',
    placement: 'collection_banner',
    status: 'active',
    priority: 35,
    sortOrder: 1,
    backgroundColor: '#1a1a2e',
    textColor: '#ffffff',
    overlayOpacity: 30,
  },
  // Announcement Bars
  {
    title: 'New: AI-Powered Analytics Dashboard Now Available',
    description: 'Get real-time insights with our latest release',
    imageUrl: '',
    ctaText: 'Learn More',
    ctaUrl: '/blog/ai-analytics-launch',
    placement: 'announcement_bar',
    status: 'active',
    priority: 100,
    sortOrder: 0,
    backgroundColor: '#7c3aed',
    textColor: '#ffffff',
    overlayOpacity: 0,
  },
  {
    title: 'Use code TECH20 for 20% off your first project',
    description: 'Limited time offer for new clients',
    imageUrl: '',
    ctaText: 'Get Started',
    ctaUrl: '/contact',
    placement: 'announcement_bar',
    status: 'active',
    priority: 90,
    sortOrder: 1,
    backgroundColor: '#059669',
    textColor: '#ffffff',
    overlayOpacity: 0,
  },
  // Scheduled Banner
  {
    title: 'Black Friday: 30% Off All Services',
    description: 'Biggest sale of the year on all technology services',
    imageUrl: 'https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?w=1920&h=800&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1607083206869-4c7672e72a8a?w=640&h=800&fit=crop',
    ctaText: 'Shop Now',
    ctaUrl: '/products',
    placement: 'homepage_hero',
    status: 'scheduled',
    startDate: new Date('2025-11-25'),
    endDate: new Date('2025-12-02'),
    priority: 150,
    sortOrder: 0,
    backgroundColor: '#000000',
    textColor: '#ffffff',
    overlayOpacity: 50,
  },
  // Draft Banner
  {
    title: 'Coming Soon: Kubernetes Management Platform',
    description: 'Next-generation container orchestration made simple',
    imageUrl: 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=1920&h=800&fit=crop',
    ctaText: 'Join Waitlist',
    ctaUrl: '/waitlist/k8s-platform',
    placement: 'homepage_hero',
    status: 'draft',
    priority: 0,
    sortOrder: 10,
    backgroundColor: '#1a1a2e',
    textColor: '#ffffff',
    overlayOpacity: 40,
  },
];

// ColorPark - Creative Design Agency
const colorparkBanners: BannerData[] = [
  // Homepage Hero Banners
  {
    title: 'Design That Inspires',
    description: 'Transform your brand with award-winning creative design that captures attention and drives results.',
    imageUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=1920&h=800&fit=crop',
    imageUrlTablet: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=1024&h=600&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=640&h=800&fit=crop',
    ctaText: 'View Our Work',
    ctaUrl: '/products',
    placement: 'homepage_hero',
    status: 'active',
    priority: 100,
    sortOrder: 0,
    backgroundColor: '#ffffff',
    textColor: '#1a1a1a',
    overlayOpacity: 20,
  },
  {
    title: 'Brand Identity Packages',
    description: 'Complete branding solutions including logo design, color palette, typography, and brand guidelines.',
    imageUrl: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=1920&h=800&fit=crop',
    imageUrlTablet: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=1024&h=600&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=640&h=800&fit=crop',
    ctaText: 'Explore Branding',
    ctaUrl: '/products?category=brand-identity',
    placement: 'homepage_hero',
    status: 'active',
    priority: 90,
    sortOrder: 1,
    backgroundColor: '#f8f9fa',
    textColor: '#2d3436',
    overlayOpacity: 15,
  },
  {
    title: 'UI/UX That Converts',
    description: 'User-centered design that delights users and drives business growth through intuitive experiences.',
    imageUrl: 'https://images.unsplash.com/photo-1545235617-9465d2a55698?w=1920&h=800&fit=crop',
    imageUrlTablet: 'https://images.unsplash.com/photo-1545235617-9465d2a55698?w=1024&h=600&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1545235617-9465d2a55698?w=640&h=800&fit=crop',
    ctaText: 'See UI/UX Services',
    ctaUrl: '/products?category=ui-ux-design',
    placement: 'homepage_hero',
    status: 'active',
    priority: 80,
    sortOrder: 2,
    backgroundColor: '#1a1a1a',
    textColor: '#ffffff',
    overlayOpacity: 30,
  },
  // Section Banners
  {
    title: 'Logo Design Starting at $299',
    description: 'Professional logo design with unlimited revisions and full ownership rights.',
    imageUrl: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=1200&h=400&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=640&h=400&fit=crop',
    ctaText: 'Start Your Project',
    ctaUrl: '/products?category=logo-design',
    placement: 'section_banner',
    status: 'active',
    priority: 50,
    sortOrder: 0,
    backgroundColor: '#ff6b6b',
    textColor: '#ffffff',
    overlayOpacity: 25,
  },
  {
    title: 'Free Brand Audit',
    description: 'Get a comprehensive analysis of your current brand presence and recommendations.',
    imageUrl: 'https://images.unsplash.com/photo-1542744094-3a31f272c490?w=1200&h=400&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1542744094-3a31f272c490?w=640&h=400&fit=crop',
    ctaText: 'Request Audit',
    ctaUrl: '/contact',
    placement: 'section_banner',
    status: 'active',
    priority: 45,
    sortOrder: 1,
    backgroundColor: '#6c5ce7',
    textColor: '#ffffff',
    overlayOpacity: 20,
  },
  // Collection Banners
  {
    title: 'Logo & Branding',
    description: 'Create a memorable first impression',
    imageUrl: 'https://images.unsplash.com/photo-1600132806370-bf17e65e942f?w=800&h=600&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1600132806370-bf17e65e942f?w=400&h=400&fit=crop',
    ctaText: 'View Packages',
    ctaUrl: '/products?category=logo-design',
    placement: 'collection_banner',
    status: 'active',
    priority: 40,
    sortOrder: 0,
    backgroundColor: '#fdcb6e',
    textColor: '#2d3436',
    overlayOpacity: 20,
  },
  {
    title: 'Web Design',
    description: 'Beautiful websites that perform',
    imageUrl: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&h=600&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=400&h=400&fit=crop',
    ctaText: 'See Examples',
    ctaUrl: '/products?category=web-design',
    placement: 'collection_banner',
    status: 'active',
    priority: 35,
    sortOrder: 1,
    backgroundColor: '#00cec9',
    textColor: '#ffffff',
    overlayOpacity: 25,
  },
  {
    title: 'Social Media Graphics',
    description: 'Stand out on every platform',
    imageUrl: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=800&h=600&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=400&h=400&fit=crop',
    ctaText: 'Browse Templates',
    ctaUrl: '/products?category=social-media',
    placement: 'collection_banner',
    status: 'active',
    priority: 30,
    sortOrder: 2,
    backgroundColor: '#e84393',
    textColor: '#ffffff',
    overlayOpacity: 20,
  },
  // Announcement Bars
  {
    title: 'New Portfolio: Check out our latest projects',
    description: 'Fresh designs added weekly',
    imageUrl: '',
    ctaText: 'View Portfolio',
    ctaUrl: '/portfolio',
    placement: 'announcement_bar',
    status: 'active',
    priority: 100,
    sortOrder: 0,
    backgroundColor: '#6c5ce7',
    textColor: '#ffffff',
    overlayOpacity: 0,
  },
  {
    title: 'Use code DESIGN15 for 15% off all packages',
    description: 'Limited time offer',
    imageUrl: '',
    ctaText: 'Shop Now',
    ctaUrl: '/products',
    placement: 'announcement_bar',
    status: 'active',
    priority: 90,
    sortOrder: 1,
    backgroundColor: '#00b894',
    textColor: '#ffffff',
    overlayOpacity: 0,
  },
  // Scheduled Banner
  {
    title: 'Holiday Special: 25% Off Branding Packages',
    description: 'Start the new year with a fresh brand identity',
    imageUrl: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=1920&h=800&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=640&h=800&fit=crop',
    ctaText: 'Claim Offer',
    ctaUrl: '/products',
    placement: 'homepage_hero',
    status: 'scheduled',
    startDate: new Date('2025-12-15'),
    endDate: new Date('2026-01-05'),
    priority: 150,
    sortOrder: 0,
    backgroundColor: '#c0392b',
    textColor: '#ffffff',
    overlayOpacity: 40,
  },
  // Draft Banner
  {
    title: 'Coming Soon: AI-Powered Design Tools',
    description: 'Generate brand assets instantly with our new AI design suite',
    imageUrl: 'https://images.unsplash.com/photo-1633356122102-3fe601e05bd2?w=1920&h=800&fit=crop',
    ctaText: 'Get Early Access',
    ctaUrl: '/waitlist/ai-design',
    placement: 'homepage_hero',
    status: 'draft',
    priority: 0,
    sortOrder: 10,
    backgroundColor: '#2d3436',
    textColor: '#ffffff',
    overlayOpacity: 35,
  },
];

// xCyberSecurity - Cybersecurity Services
const xcybersecurityBanners: BannerData[] = [
  // Homepage Hero Banners
  {
    title: 'Defend Your Digital Assets',
    description: 'Enterprise-grade cybersecurity solutions to protect your organization from evolving threats.',
    imageUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=1920&h=800&fit=crop',
    imageUrlTablet: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=1024&h=600&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=640&h=800&fit=crop',
    ctaText: 'Get Protected',
    ctaUrl: '/products',
    placement: 'homepage_hero',
    status: 'active',
    priority: 100,
    sortOrder: 0,
    backgroundColor: '#0a0a0a',
    textColor: '#00ff88',
    overlayOpacity: 50,
  },
  {
    title: 'Penetration Testing Services',
    description: 'Find vulnerabilities before attackers do with our expert red team assessments.',
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1920&h=800&fit=crop',
    imageUrlTablet: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1024&h=600&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=640&h=800&fit=crop',
    ctaText: 'Request Assessment',
    ctaUrl: '/products?category=penetration-testing',
    placement: 'homepage_hero',
    status: 'active',
    priority: 90,
    sortOrder: 1,
    backgroundColor: '#1a1a2e',
    textColor: '#ffffff',
    overlayOpacity: 45,
  },
  {
    title: '24/7 Security Operations Center',
    description: 'Round-the-clock monitoring, detection, and response to keep your systems secure.',
    imageUrl: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=1920&h=800&fit=crop',
    imageUrlTablet: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=1024&h=600&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=640&h=800&fit=crop',
    ctaText: 'Learn About SOC',
    ctaUrl: '/products?category=managed-security',
    placement: 'homepage_hero',
    status: 'active',
    priority: 80,
    sortOrder: 2,
    backgroundColor: '#0d1117',
    textColor: '#58a6ff',
    overlayOpacity: 40,
  },
  // Section Banners
  {
    title: 'Free Security Assessment',
    description: 'Discover vulnerabilities in your infrastructure with a complimentary security scan.',
    imageUrl: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=1200&h=400&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=640&h=400&fit=crop',
    ctaText: 'Start Free Scan',
    ctaUrl: '/contact',
    placement: 'section_banner',
    status: 'active',
    priority: 50,
    sortOrder: 0,
    backgroundColor: '#dc2626',
    textColor: '#ffffff',
    overlayOpacity: 30,
  },
  {
    title: 'Compliance Made Simple',
    description: 'SOC 2, ISO 27001, HIPAA, PCI DSS - We guide you through every step.',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1200&h=400&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=640&h=400&fit=crop',
    ctaText: 'View Compliance Services',
    ctaUrl: '/products?category=compliance',
    placement: 'section_banner',
    status: 'active',
    priority: 45,
    sortOrder: 1,
    backgroundColor: '#1e40af',
    textColor: '#ffffff',
    overlayOpacity: 25,
  },
  // Collection Banners
  {
    title: 'Penetration Testing',
    description: 'Web, network, and mobile security assessments',
    imageUrl: 'https://images.unsplash.com/photo-1510511459019-5dda7724fd87?w=800&h=600&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1510511459019-5dda7724fd87?w=400&h=400&fit=crop',
    ctaText: 'View Services',
    ctaUrl: '/products?category=penetration-testing',
    placement: 'collection_banner',
    status: 'active',
    priority: 40,
    sortOrder: 0,
    backgroundColor: '#dc2626',
    textColor: '#ffffff',
    overlayOpacity: 35,
  },
  {
    title: 'Managed Security',
    description: '24/7 monitoring and incident response',
    imageUrl: 'https://images.unsplash.com/photo-1551808525-51a94da548ce?w=800&h=600&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1551808525-51a94da548ce?w=400&h=400&fit=crop',
    ctaText: 'Explore Plans',
    ctaUrl: '/products?category=managed-security',
    placement: 'collection_banner',
    status: 'active',
    priority: 35,
    sortOrder: 1,
    backgroundColor: '#0ea5e9',
    textColor: '#ffffff',
    overlayOpacity: 30,
  },
  {
    title: 'Security Training',
    description: 'Empower your team against threats',
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=600&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&h=400&fit=crop',
    ctaText: 'Browse Courses',
    ctaUrl: '/products?category=security-training',
    placement: 'collection_banner',
    status: 'active',
    priority: 30,
    sortOrder: 2,
    backgroundColor: '#7c3aed',
    textColor: '#ffffff',
    overlayOpacity: 25,
  },
  // Announcement Bars
  {
    title: 'Security Alert: New zero-day vulnerability discovered - Read our advisory',
    description: 'Stay informed about the latest threats',
    imageUrl: '',
    ctaText: 'Read Advisory',
    ctaUrl: '/blog/security-advisory',
    placement: 'announcement_bar',
    status: 'active',
    priority: 100,
    sortOrder: 0,
    backgroundColor: '#dc2626',
    textColor: '#ffffff',
    overlayOpacity: 0,
  },
  {
    title: 'Use code SECURE20 for 20% off your first assessment',
    description: 'New client special offer',
    imageUrl: '',
    ctaText: 'Get Started',
    ctaUrl: '/contact',
    placement: 'announcement_bar',
    status: 'active',
    priority: 90,
    sortOrder: 1,
    backgroundColor: '#059669',
    textColor: '#ffffff',
    overlayOpacity: 0,
  },
  // Scheduled Banner
  {
    title: 'Cyber Monday: 35% Off All Security Packages',
    description: 'Protect your business at unbeatable prices',
    imageUrl: 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=1920&h=800&fit=crop',
    imageUrlMobile: 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=640&h=800&fit=crop',
    ctaText: 'Claim Deal',
    ctaUrl: '/products',
    placement: 'homepage_hero',
    status: 'scheduled',
    startDate: new Date('2025-12-01'),
    endDate: new Date('2025-12-03'),
    priority: 150,
    sortOrder: 0,
    backgroundColor: '#000000',
    textColor: '#00ff88',
    overlayOpacity: 55,
  },
  // Draft Banner
  {
    title: 'Coming Soon: AI-Powered Threat Detection',
    description: 'Next-generation security with machine learning threat analysis',
    imageUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=1920&h=800&fit=crop',
    ctaText: 'Join Beta',
    ctaUrl: '/waitlist/ai-threat-detection',
    placement: 'homepage_hero',
    status: 'draft',
    priority: 0,
    sortOrder: 10,
    backgroundColor: '#0d1117',
    textColor: '#58a6ff',
    overlayOpacity: 45,
  },
];

// Store banner mapping
const storeBanners: Record<string, BannerData[]> = {
  ramlit: ramlitBanners,
  colorpark: colorparkBanners,
  xcybersecurity: xcybersecurityBanners,
};

export async function seedBanners(prisma: PrismaClient, stores: Record<string, Store>) {
  console.log('  Creating banners for all stores...');

  let totalBanners = 0;

  for (const [storeKey, store] of Object.entries(stores)) {
    const banners = storeBanners[storeKey];
    if (!banners) continue;

    for (const bannerData of banners) {
      await prisma.banner.create({
        data: {
          storeId: store.id,
          title: bannerData.title,
          description: bannerData.description || null,
          imageUrl: bannerData.imageUrl || null,
          imageUrlTablet: bannerData.imageUrlTablet || null,
          imageUrlMobile: bannerData.imageUrlMobile || null,
          ctaText: bannerData.ctaText || null,
          ctaUrl: bannerData.ctaUrl || null,
          ctaTarget: bannerData.ctaTarget || '_self',
          placement: bannerData.placement,
          status: bannerData.status,
          startDate: bannerData.startDate || null,
          endDate: bannerData.endDate || null,
          priority: bannerData.priority,
          sortOrder: bannerData.sortOrder,
          backgroundColor: bannerData.backgroundColor || null,
          textColor: bannerData.textColor || null,
          overlayOpacity: bannerData.overlayOpacity || 0,
          metadata: bannerData.metadata || {},
        },
      });
      totalBanners++;
    }
  }

  console.log(`  Created ${totalBanners} banners across all stores`);
}
