import { PrismaClient, Store } from '@prisma/client';

// Product data for Ramlit Limited (IT Services & Software)
const ramlitProducts = [
  // AI & Machine Learning Services
  {
    name: 'AI Integration Starter Package',
    slug: 'ai-integration-starter',
    description: 'Comprehensive AI integration service for small to medium businesses. Includes initial assessment, custom AI model development, integration with existing systems, and 30 days of support. Perfect for companies looking to automate routine tasks and gain data-driven insights.',
    shortDescription: 'AI integration for SMBs with custom model development',
    sku: 'RML-AI-001',
    price: 4999.00,
    compareAtPrice: 5999.00,
    quantity: 100,
    status: 'active',
    category: 'AI & Machine Learning',
    tags: ['ai', 'machine-learning', 'automation', 'starter'],
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800',
  },
  {
    name: 'Enterprise AI Platform License',
    slug: 'enterprise-ai-platform',
    description: 'Full-featured enterprise AI platform with unlimited users, advanced analytics, natural language processing, computer vision capabilities, and dedicated infrastructure. Includes 24/7 support and quarterly optimization reviews.',
    shortDescription: 'Enterprise-grade AI platform with unlimited users',
    sku: 'RML-AI-002',
    price: 24999.00,
    compareAtPrice: 29999.00,
    quantity: 50,
    status: 'active',
    category: 'AI & Machine Learning',
    tags: ['ai', 'enterprise', 'nlp', 'computer-vision'],
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800',
  },
  {
    name: 'Machine Learning Model Training',
    slug: 'ml-model-training',
    description: 'Custom machine learning model training service. Our data scientists will analyze your data, develop and train custom ML models, and deploy them to production. Includes model monitoring and retraining recommendations.',
    shortDescription: 'Custom ML model development and training',
    sku: 'RML-AI-003',
    price: 9999.00,
    compareAtPrice: null,
    quantity: 75,
    status: 'active',
    category: 'AI & Machine Learning',
    tags: ['machine-learning', 'data-science', 'custom'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800',
  },
  // DevOps Services
  {
    name: 'DevOps Pipeline Setup',
    slug: 'devops-pipeline-setup',
    description: 'Complete CI/CD pipeline setup including version control integration, automated testing, staging environments, and production deployment automation. Supports AWS, Azure, GCP, and on-premise infrastructure.',
    shortDescription: 'Complete CI/CD pipeline implementation',
    sku: 'RML-DO-001',
    price: 7999.00,
    compareAtPrice: 9499.00,
    quantity: 80,
    status: 'active',
    category: 'DevOps',
    tags: ['devops', 'ci-cd', 'automation', 'deployment'],
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=800',
  },
  {
    name: 'Kubernetes Migration Service',
    slug: 'kubernetes-migration',
    description: 'Full-service Kubernetes migration including architecture assessment, containerization strategy, cluster setup, application migration, and team training. Zero-downtime migration guaranteed.',
    shortDescription: 'Complete Kubernetes migration with zero downtime',
    sku: 'RML-DO-002',
    price: 14999.00,
    compareAtPrice: 17999.00,
    quantity: 40,
    status: 'active',
    category: 'DevOps',
    tags: ['kubernetes', 'containers', 'migration', 'docker'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1605745341112-85968b19335b?w=800',
  },
  {
    name: 'Infrastructure as Code Implementation',
    slug: 'infrastructure-as-code',
    description: 'Transform your infrastructure management with IaC. Includes Terraform or Pulumi implementation, existing infrastructure import, modular code structure, and documentation. Enables reproducible and version-controlled infrastructure.',
    shortDescription: 'Terraform/Pulumi IaC implementation',
    sku: 'RML-DO-003',
    price: 5999.00,
    compareAtPrice: null,
    quantity: 90,
    status: 'active',
    category: 'DevOps',
    tags: ['terraform', 'iac', 'infrastructure', 'pulumi'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800',
  },
  // Cloud Services
  {
    name: 'Cloud Architecture Design',
    slug: 'cloud-architecture-design',
    description: 'Expert cloud architecture design service for scalable, secure, and cost-effective solutions. Includes multi-cloud strategy, disaster recovery planning, and detailed implementation roadmap. Optimized for AWS, Azure, or GCP.',
    shortDescription: 'Enterprise cloud architecture design',
    sku: 'RML-CL-001',
    price: 12999.00,
    compareAtPrice: 15999.00,
    quantity: 60,
    status: 'active',
    category: 'Cloud Services',
    tags: ['cloud', 'architecture', 'aws', 'azure', 'gcp'],
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800',
  },
  {
    name: 'Cloud Migration Package',
    slug: 'cloud-migration-package',
    description: 'End-to-end cloud migration service covering assessment, planning, execution, and optimization. Includes application modernization recommendations, data migration, and post-migration support.',
    shortDescription: 'Complete cloud migration service',
    sku: 'RML-CL-002',
    price: 19999.00,
    compareAtPrice: 24999.00,
    quantity: 45,
    status: 'active',
    category: 'Cloud Services',
    tags: ['cloud', 'migration', 'modernization'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1639322537228-f710d846310a?w=800',
  },
  {
    name: 'Serverless Application Development',
    slug: 'serverless-development',
    description: 'Build scalable, cost-effective applications using serverless architecture. Includes Lambda/Functions design, API Gateway setup, event-driven architecture, and performance optimization.',
    shortDescription: 'Serverless application development',
    sku: 'RML-CL-003',
    price: 8999.00,
    compareAtPrice: null,
    quantity: 70,
    status: 'active',
    category: 'Cloud Services',
    tags: ['serverless', 'lambda', 'functions', 'api'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800',
  },
  // Software Development
  {
    name: 'Custom Software Development',
    slug: 'custom-software-development',
    description: 'Bespoke software development tailored to your business needs. Full-stack development using modern technologies, agile methodology, and continuous delivery. From MVP to enterprise-scale applications.',
    shortDescription: 'Tailored software development services',
    sku: 'RML-SD-001',
    price: 29999.00,
    compareAtPrice: null,
    quantity: 30,
    status: 'active',
    category: 'Software Development',
    tags: ['software', 'development', 'custom', 'full-stack'],
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800',
  },
  {
    name: 'API Development & Integration',
    slug: 'api-development-integration',
    description: 'Professional API development and third-party integration services. RESTful and GraphQL API design, documentation, security implementation, and integration with existing systems.',
    shortDescription: 'REST/GraphQL API development',
    sku: 'RML-SD-002',
    price: 6999.00,
    compareAtPrice: 8499.00,
    quantity: 85,
    status: 'active',
    category: 'Software Development',
    tags: ['api', 'rest', 'graphql', 'integration'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800',
  },
  {
    name: 'Mobile App Development',
    slug: 'mobile-app-development',
    description: 'Cross-platform mobile application development using React Native or Flutter. Includes UI/UX design, backend integration, app store deployment, and post-launch support.',
    shortDescription: 'Cross-platform mobile app development',
    sku: 'RML-SD-003',
    price: 34999.00,
    compareAtPrice: 39999.00,
    quantity: 25,
    status: 'active',
    category: 'Software Development',
    tags: ['mobile', 'react-native', 'flutter', 'app'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800',
  },
  // Consulting & Support
  {
    name: 'Technology Consulting (Monthly)',
    slug: 'technology-consulting-monthly',
    description: 'Ongoing technology consulting with dedicated senior consultant. Strategic planning, technology roadmap development, vendor evaluation, and digital transformation guidance. 20 hours per month.',
    shortDescription: 'Monthly technology consulting service',
    sku: 'RML-CS-001',
    price: 4999.00,
    compareAtPrice: null,
    quantity: 100,
    status: 'active',
    category: 'Consulting',
    tags: ['consulting', 'strategy', 'technology'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800',
  },
  {
    name: '24/7 Technical Support Package',
    slug: 'technical-support-247',
    description: 'Round-the-clock technical support for your IT infrastructure. Includes incident management, problem resolution, change management, and monthly reporting. SLA-backed response times.',
    shortDescription: '24/7 IT support with SLA guarantee',
    sku: 'RML-CS-002',
    price: 2999.00,
    compareAtPrice: 3499.00,
    quantity: 150,
    status: 'active',
    category: 'Consulting',
    tags: ['support', '24-7', 'sla', 'managed'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800',
  },
  {
    name: 'Security Audit & Assessment',
    slug: 'security-audit-assessment',
    description: 'Comprehensive security audit covering infrastructure, applications, and processes. Includes vulnerability scanning, risk assessment, compliance review, and detailed remediation roadmap.',
    shortDescription: 'Complete security audit and assessment',
    sku: 'RML-CS-003',
    price: 8999.00,
    compareAtPrice: 10999.00,
    quantity: 65,
    status: 'active',
    category: 'Consulting',
    tags: ['security', 'audit', 'compliance', 'assessment'],
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800',
  },
];

// Product data for ColorPark (Design Services)
const colorparkProducts = [
  // Logo & Branding
  {
    name: 'Logo Design Package - Essential',
    slug: 'logo-design-essential',
    description: 'Professional logo design package including 3 initial concepts, 2 revision rounds, final files in all formats (AI, EPS, PNG, JPG, SVG), brand color palette, and typography recommendations.',
    shortDescription: 'Professional logo design with 3 concepts',
    sku: 'CP-LB-001',
    price: 499.00,
    compareAtPrice: 699.00,
    quantity: 200,
    status: 'active',
    category: 'Logo & Branding',
    tags: ['logo', 'branding', 'design', 'essential'],
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800',
  },
  {
    name: 'Logo Design Package - Premium',
    slug: 'logo-design-premium',
    description: 'Premium logo design package with 5 initial concepts, unlimited revisions, complete brand identity package including business card design, letterhead, and social media profile images.',
    shortDescription: 'Premium logo with complete brand identity',
    sku: 'CP-LB-002',
    price: 999.00,
    compareAtPrice: 1299.00,
    quantity: 150,
    status: 'active',
    category: 'Logo & Branding',
    tags: ['logo', 'branding', 'premium', 'identity'],
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800',
  },
  {
    name: 'Complete Brand Identity System',
    slug: 'complete-brand-identity',
    description: 'Full brand identity development including logo system, color palette, typography hierarchy, brand guidelines document, stationery design, and brand asset library. Perfect for new businesses or rebranding.',
    shortDescription: 'Complete brand identity development',
    sku: 'CP-LB-003',
    price: 2999.00,
    compareAtPrice: 3999.00,
    quantity: 80,
    status: 'active',
    category: 'Logo & Branding',
    tags: ['branding', 'identity', 'guidelines', 'complete'],
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=800',
  },
  {
    name: 'Brand Refresh Package',
    slug: 'brand-refresh',
    description: 'Modernize your existing brand without losing recognition. Includes logo refinement, updated color palette, refreshed typography, and transition guidelines for smooth brand evolution.',
    shortDescription: 'Modernize your existing brand identity',
    sku: 'CP-LB-004',
    price: 1499.00,
    compareAtPrice: null,
    quantity: 100,
    status: 'active',
    category: 'Logo & Branding',
    tags: ['branding', 'refresh', 'modernize'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800',
  },
  // UI/UX Design
  {
    name: 'Website UI/UX Design',
    slug: 'website-ui-ux-design',
    description: 'Complete website UI/UX design including user research, wireframes, high-fidelity mockups, interactive prototype, and developer-ready design files. Responsive design for all devices.',
    shortDescription: 'Complete website UI/UX design',
    sku: 'CP-UX-001',
    price: 3999.00,
    compareAtPrice: 4999.00,
    quantity: 60,
    status: 'active',
    category: 'UI/UX Design',
    tags: ['ui', 'ux', 'website', 'responsive'],
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800',
  },
  {
    name: 'Mobile App UI Design',
    slug: 'mobile-app-ui-design',
    description: 'Native mobile app UI design for iOS and Android. Includes user flow mapping, wireframes, high-fidelity screens, component library, and animation specifications. Follows platform guidelines.',
    shortDescription: 'iOS and Android app UI design',
    sku: 'CP-UX-002',
    price: 4999.00,
    compareAtPrice: 5999.00,
    quantity: 50,
    status: 'active',
    category: 'UI/UX Design',
    tags: ['ui', 'mobile', 'ios', 'android', 'app'],
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800',
  },
  {
    name: 'Dashboard & Admin Panel Design',
    slug: 'dashboard-admin-design',
    description: 'Data-rich dashboard and admin panel design with focus on usability and information hierarchy. Includes data visualization components, user management interfaces, and reporting screens.',
    shortDescription: 'Dashboard and admin panel UI design',
    sku: 'CP-UX-003',
    price: 2999.00,
    compareAtPrice: null,
    quantity: 70,
    status: 'active',
    category: 'UI/UX Design',
    tags: ['dashboard', 'admin', 'data-visualization', 'ui'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
  },
  {
    name: 'UX Audit & Recommendations',
    slug: 'ux-audit',
    description: 'Comprehensive UX audit of your existing product. Includes heuristic evaluation, usability analysis, competitive analysis, and detailed recommendations with prioritized improvement roadmap.',
    shortDescription: 'Complete UX audit with recommendations',
    sku: 'CP-UX-004',
    price: 1499.00,
    compareAtPrice: 1999.00,
    quantity: 90,
    status: 'active',
    category: 'UI/UX Design',
    tags: ['ux', 'audit', 'usability', 'analysis'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=800',
  },
  // Web Design
  {
    name: 'Landing Page Design',
    slug: 'landing-page-design',
    description: 'High-converting landing page design optimized for conversions. Includes A/B testing recommendations, mobile optimization, and integration-ready design for popular builders.',
    shortDescription: 'Conversion-optimized landing page design',
    sku: 'CP-WD-001',
    price: 899.00,
    compareAtPrice: 1199.00,
    quantity: 120,
    status: 'active',
    category: 'Web Design',
    tags: ['landing-page', 'conversion', 'web', 'design'],
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800',
  },
  {
    name: 'E-commerce Website Design',
    slug: 'ecommerce-website-design',
    description: 'Complete e-commerce website design with product pages, shopping cart, checkout flow, and account management. Optimized for Shopify, WooCommerce, or custom platforms.',
    shortDescription: 'Complete e-commerce website design',
    sku: 'CP-WD-002',
    price: 5999.00,
    compareAtPrice: 7499.00,
    quantity: 40,
    status: 'active',
    category: 'Web Design',
    tags: ['ecommerce', 'shopify', 'woocommerce', 'web'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800',
  },
  {
    name: 'Corporate Website Design',
    slug: 'corporate-website-design',
    description: 'Professional corporate website design including homepage, about, services, team, blog, and contact pages. Clean, modern aesthetic with focus on credibility and trust.',
    shortDescription: 'Professional corporate website design',
    sku: 'CP-WD-003',
    price: 3499.00,
    compareAtPrice: 4499.00,
    quantity: 55,
    status: 'active',
    category: 'Web Design',
    tags: ['corporate', 'website', 'professional', 'business'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800',
  },
  // Social Media & Graphics
  {
    name: 'Social Media Design Pack',
    slug: 'social-media-design-pack',
    description: 'Complete social media graphics package including 20 post templates, 10 story templates, profile images, and cover photos for all major platforms. Editable Canva or Figma files included.',
    shortDescription: 'Complete social media template pack',
    sku: 'CP-SM-001',
    price: 699.00,
    compareAtPrice: 899.00,
    quantity: 180,
    status: 'active',
    category: 'Social Media',
    tags: ['social-media', 'templates', 'instagram', 'facebook'],
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=800',
  },
  {
    name: 'Monthly Social Media Graphics',
    slug: 'monthly-social-media-graphics',
    description: 'Monthly social media content creation service. 30 custom posts, 15 stories, and seasonal content aligned with your brand. Perfect for consistent social presence.',
    shortDescription: 'Monthly social media content creation',
    sku: 'CP-SM-002',
    price: 1299.00,
    compareAtPrice: null,
    quantity: 100,
    status: 'active',
    category: 'Social Media',
    tags: ['social-media', 'monthly', 'content', 'management'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=800',
  },
  // Illustration & Graphics
  {
    name: 'Custom Illustration Package',
    slug: 'custom-illustration-package',
    description: 'Bespoke illustration service for brands. Includes 10 custom illustrations in your brand style, suitable for website, marketing materials, and social media.',
    shortDescription: 'Custom brand illustration package',
    sku: 'CP-IL-001',
    price: 1999.00,
    compareAtPrice: 2499.00,
    quantity: 75,
    status: 'active',
    category: 'Illustration',
    tags: ['illustration', 'custom', 'brand', 'art'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800',
  },
  {
    name: 'Icon Set Design',
    slug: 'icon-set-design',
    description: 'Custom icon set design with 50 unique icons in your brand style. Delivered in multiple formats (SVG, PNG) and sizes. Perfect for websites, apps, and presentations.',
    shortDescription: '50 custom icons in brand style',
    sku: 'CP-IL-002',
    price: 799.00,
    compareAtPrice: 999.00,
    quantity: 95,
    status: 'active',
    category: 'Illustration',
    tags: ['icons', 'custom', 'svg', 'design'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?w=800',
  },
  // Packaging
  {
    name: 'Product Packaging Design',
    slug: 'product-packaging-design',
    description: 'Eye-catching product packaging design that sells. Includes primary packaging, secondary packaging concepts, and print-ready files. 3D mockups included for presentation.',
    shortDescription: 'Complete product packaging design',
    sku: 'CP-PK-001',
    price: 1499.00,
    compareAtPrice: 1999.00,
    quantity: 85,
    status: 'active',
    category: 'Packaging',
    tags: ['packaging', 'product', 'print', 'design'],
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1605732562742-3023a888e56e?w=800',
  },
  {
    name: 'Label Design',
    slug: 'label-design',
    description: 'Professional label design for products, bottles, jars, and containers. Includes design concepts, material recommendations, and print specifications.',
    shortDescription: 'Professional product label design',
    sku: 'CP-PK-002',
    price: 599.00,
    compareAtPrice: 799.00,
    quantity: 110,
    status: 'active',
    category: 'Packaging',
    tags: ['label', 'packaging', 'product', 'print'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1607082349566-187342175e2f?w=800',
  },
];

// Product data for xCyberSecurity (Security Services)
const xcybersecurityProducts = [
  // Penetration Testing
  {
    name: 'Web Application Penetration Test',
    slug: 'web-app-pentest',
    description: 'Comprehensive web application security assessment following OWASP methodologies. Includes vulnerability identification, exploitation attempts, and detailed remediation guidance. Final report with executive summary and technical details.',
    shortDescription: 'OWASP-compliant web app security testing',
    sku: 'XCS-PT-001',
    price: 4999.00,
    compareAtPrice: 5999.00,
    quantity: 100,
    status: 'active',
    category: 'Penetration Testing',
    tags: ['pentest', 'web', 'owasp', 'security'],
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=800',
  },
  {
    name: 'Network Penetration Test',
    slug: 'network-pentest',
    description: 'External and internal network penetration testing to identify vulnerabilities in your network infrastructure. Includes port scanning, service enumeration, vulnerability exploitation, and privilege escalation attempts.',
    shortDescription: 'Complete network security assessment',
    sku: 'XCS-PT-002',
    price: 7999.00,
    compareAtPrice: 9999.00,
    quantity: 75,
    status: 'active',
    category: 'Penetration Testing',
    tags: ['pentest', 'network', 'infrastructure', 'security'],
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800',
  },
  {
    name: 'Mobile Application Security Test',
    slug: 'mobile-app-security-test',
    description: 'In-depth security assessment of iOS and Android applications. Covers static and dynamic analysis, API security, data storage, network communications, and authentication mechanisms.',
    shortDescription: 'iOS and Android security testing',
    sku: 'XCS-PT-003',
    price: 5999.00,
    compareAtPrice: 7499.00,
    quantity: 60,
    status: 'active',
    category: 'Penetration Testing',
    tags: ['mobile', 'ios', 'android', 'security', 'pentest'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1526498460520-4c246339dccb?w=800',
  },
  {
    name: 'API Security Assessment',
    slug: 'api-security-assessment',
    description: 'Thorough security testing of REST and GraphQL APIs. Covers authentication, authorization, injection attacks, rate limiting, and business logic vulnerabilities. Includes API documentation review.',
    shortDescription: 'REST/GraphQL API security testing',
    sku: 'XCS-PT-004',
    price: 3999.00,
    compareAtPrice: null,
    quantity: 85,
    status: 'active',
    category: 'Penetration Testing',
    tags: ['api', 'rest', 'graphql', 'security'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800',
  },
  {
    name: 'Red Team Engagement',
    slug: 'red-team-engagement',
    description: 'Full-scope adversary simulation covering physical, social, and technical attack vectors. Simulates real-world attack scenarios to test your organization\'s detection and response capabilities.',
    shortDescription: 'Full-scope adversary simulation',
    sku: 'XCS-PT-005',
    price: 24999.00,
    compareAtPrice: 29999.00,
    quantity: 25,
    status: 'active',
    category: 'Penetration Testing',
    tags: ['red-team', 'adversary', 'simulation', 'advanced'],
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800',
  },
  // Vulnerability Assessment
  {
    name: 'Vulnerability Assessment - Standard',
    slug: 'vulnerability-assessment-standard',
    description: 'Automated vulnerability scanning with manual verification. Covers up to 100 IP addresses or web pages. Includes vulnerability prioritization and remediation recommendations.',
    shortDescription: 'Standard vulnerability scanning service',
    sku: 'XCS-VA-001',
    price: 1999.00,
    compareAtPrice: 2499.00,
    quantity: 150,
    status: 'active',
    category: 'Vulnerability Assessment',
    tags: ['vulnerability', 'scanning', 'assessment', 'standard'],
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800',
  },
  {
    name: 'Vulnerability Assessment - Enterprise',
    slug: 'vulnerability-assessment-enterprise',
    description: 'Enterprise-grade vulnerability assessment for large environments. Unlimited assets, continuous monitoring, integration with ticketing systems, and dedicated security analyst support.',
    shortDescription: 'Enterprise vulnerability management',
    sku: 'XCS-VA-002',
    price: 9999.00,
    compareAtPrice: null,
    quantity: 50,
    status: 'active',
    category: 'Vulnerability Assessment',
    tags: ['vulnerability', 'enterprise', 'continuous', 'monitoring'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=800',
  },
  {
    name: 'Cloud Security Assessment',
    slug: 'cloud-security-assessment',
    description: 'Comprehensive security review of AWS, Azure, or GCP environments. Covers IAM, network security, data protection, logging, and compliance. Based on CIS benchmarks and cloud provider best practices.',
    shortDescription: 'AWS/Azure/GCP security assessment',
    sku: 'XCS-VA-003',
    price: 6999.00,
    compareAtPrice: 8499.00,
    quantity: 65,
    status: 'active',
    category: 'Vulnerability Assessment',
    tags: ['cloud', 'aws', 'azure', 'gcp', 'security'],
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800',
  },
  // Managed Security
  {
    name: 'Managed SOC - Basic',
    slug: 'managed-soc-basic',
    description: '24/7 Security Operations Center monitoring for small businesses. Includes log collection, SIEM, threat detection, and incident alerting. Up to 50 endpoints.',
    shortDescription: '24/7 SOC monitoring for small business',
    sku: 'XCS-MS-001',
    price: 2499.00,
    compareAtPrice: 2999.00,
    quantity: 100,
    status: 'active',
    category: 'Managed Security',
    tags: ['soc', 'monitoring', '24-7', 'managed'],
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
  },
  {
    name: 'Managed SOC - Professional',
    slug: 'managed-soc-professional',
    description: 'Professional SOC service with advanced threat hunting, incident response, and forensics capabilities. Includes EDR deployment and management. Up to 500 endpoints.',
    shortDescription: 'Professional SOC with threat hunting',
    sku: 'XCS-MS-002',
    price: 7999.00,
    compareAtPrice: null,
    quantity: 60,
    status: 'active',
    category: 'Managed Security',
    tags: ['soc', 'threat-hunting', 'edr', 'professional'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800',
  },
  {
    name: 'Managed Detection & Response (MDR)',
    slug: 'managed-detection-response',
    description: 'Advanced MDR service combining cutting-edge technology with expert security analysts. Real-time threat detection, automated response, and comprehensive incident management.',
    shortDescription: 'Advanced MDR with automated response',
    sku: 'XCS-MS-003',
    price: 12999.00,
    compareAtPrice: 15999.00,
    quantity: 40,
    status: 'active',
    category: 'Managed Security',
    tags: ['mdr', 'detection', 'response', 'automated'],
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1510511459019-5dda7724fd87?w=800',
  },
  // Compliance
  {
    name: 'SOC 2 Compliance Package',
    slug: 'soc2-compliance',
    description: 'Complete SOC 2 compliance preparation including gap assessment, policy development, control implementation support, and auditor liaison. Type I or Type II preparation.',
    shortDescription: 'SOC 2 compliance preparation',
    sku: 'XCS-CP-001',
    price: 14999.00,
    compareAtPrice: 19999.00,
    quantity: 45,
    status: 'active',
    category: 'Compliance',
    tags: ['soc2', 'compliance', 'audit', 'certification'],
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800',
  },
  {
    name: 'ISO 27001 Implementation',
    slug: 'iso-27001-implementation',
    description: 'End-to-end ISO 27001 implementation support. Includes ISMS development, risk assessment, policy creation, employee training, and certification audit preparation.',
    shortDescription: 'ISO 27001 certification support',
    sku: 'XCS-CP-002',
    price: 19999.00,
    compareAtPrice: null,
    quantity: 35,
    status: 'active',
    category: 'Compliance',
    tags: ['iso27001', 'isms', 'certification', 'compliance'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800',
  },
  {
    name: 'PCI DSS Compliance Assessment',
    slug: 'pci-dss-compliance',
    description: 'PCI DSS compliance assessment and remediation support for organizations handling payment card data. Gap analysis, SAQ assistance, and QSA coordination.',
    shortDescription: 'PCI DSS compliance support',
    sku: 'XCS-CP-003',
    price: 8999.00,
    compareAtPrice: 10999.00,
    quantity: 55,
    status: 'active',
    category: 'Compliance',
    tags: ['pci-dss', 'payment', 'compliance', 'assessment'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800',
  },
  // Incident Response
  {
    name: 'Incident Response Retainer',
    slug: 'incident-response-retainer',
    description: 'Pre-arranged incident response retainer ensuring rapid expert assistance during security incidents. Includes response planning, tabletop exercises, and guaranteed response times.',
    shortDescription: 'Pre-arranged IR with guaranteed response',
    sku: 'XCS-IR-001',
    price: 4999.00,
    compareAtPrice: 5999.00,
    quantity: 80,
    status: 'active',
    category: 'Incident Response',
    tags: ['incident-response', 'retainer', 'emergency', 'security'],
    featured: true,
    imageUrl: 'https://images.unsplash.com/photo-1633265486064-086b219458ec?w=800',
  },
  {
    name: 'Digital Forensics Investigation',
    slug: 'digital-forensics',
    description: 'Professional digital forensics service for security incidents, data breaches, or legal matters. Evidence collection, analysis, chain of custody, and expert witness testimony.',
    shortDescription: 'Professional digital forensics',
    sku: 'XCS-IR-002',
    price: 9999.00,
    compareAtPrice: null,
    quantity: 50,
    status: 'active',
    category: 'Incident Response',
    tags: ['forensics', 'investigation', 'breach', 'evidence'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800',
  },
  // Training
  {
    name: 'Security Awareness Training',
    slug: 'security-awareness-training',
    description: 'Comprehensive security awareness training for employees. Includes phishing simulations, interactive modules, and compliance tracking. Annual license for up to 100 users.',
    shortDescription: 'Employee security awareness program',
    sku: 'XCS-TR-001',
    price: 1999.00,
    compareAtPrice: 2499.00,
    quantity: 120,
    status: 'active',
    category: 'Training',
    tags: ['training', 'awareness', 'phishing', 'employees'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800',
  },
  {
    name: 'Technical Security Training',
    slug: 'technical-security-training',
    description: 'Hands-on technical security training for IT teams. Covers secure coding, infrastructure hardening, incident handling, and security tools. 3-day intensive workshop.',
    shortDescription: 'Technical security workshop for IT teams',
    sku: 'XCS-TR-002',
    price: 4999.00,
    compareAtPrice: null,
    quantity: 70,
    status: 'active',
    category: 'Training',
    tags: ['training', 'technical', 'workshop', 'hands-on'],
    featured: false,
    imageUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800',
  },
];

export async function seedProducts(prisma: PrismaClient, stores: Record<string, Store>) {
  console.log('  Creating products for all stores...');

  const productConfigs: Record<string, typeof ramlitProducts> = {
    ramlit: ramlitProducts,
    colorpark: colorparkProducts,
    xcybersecurity: xcybersecurityProducts,
  };

  let totalProducts = 0;

  for (const [storeKey, products] of Object.entries(productConfigs)) {
    const store = stores[storeKey];
    if (!store) continue;

    // First, create categories for this store
    const categoriesSet = new Set(products.map(p => p.category));
    const categories = Array.from(categoriesSet);
    const categoryMap: Record<string, string> = {};

    for (const categoryName of categories) {
      const categorySlug = categoryName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '');
      const category = await prisma.category.upsert({
        where: { storeId_slug: { storeId: store.id, slug: categorySlug } },
        update: { name: categoryName },
        create: {
          storeId: store.id,
          name: categoryName,
          slug: categorySlug,
          description: `${categoryName} products and services`,
        },
      });
      categoryMap[categoryName] = category.id;
    }

    // Create products with categories
    for (const product of products) {
      await prisma.product.upsert({
        where: { storeId_slug: { storeId: store.id, slug: product.slug } },
        update: {
          name: product.name,
          description: product.description,
          shortDescription: product.shortDescription,
          price: product.price,
          compareAtPrice: product.compareAtPrice,
          quantity: product.quantity,
          status: product.status,
        },
        create: {
          storeId: store.id,
          name: product.name,
          slug: product.slug,
          description: product.description,
          shortDescription: product.shortDescription,
          sku: product.sku,
          price: product.price,
          compareAtPrice: product.compareAtPrice,
          quantity: product.quantity,
          status: product.status,
          type: 'simple',
          trackInventory: false, // Services don't need inventory tracking
          attributes: JSON.stringify({ tags: product.tags, featured: product.featured }),
          metadata: JSON.stringify({ tags: product.tags, featured: product.featured }),
          categories: {
            create: { categoryId: categoryMap[product.category] },
          },
          images: {
            create: [{ url: product.imageUrl, position: 0, altText: product.name }],
          },
        },
      });
      totalProducts++;
    }
  }

  console.log(`  Created ${totalProducts} products across all stores`);
}
